apiVersion: v1
kind: Secret
metadata:
  name: ledgerly-secrets
  namespace: ledgerly
type: Opaque
stringData:
  DATABASE_URL: "postgres://pgadmin:YOUR_PASSWORD@expense-pg.postgres.database.azure.com:5432/expensesdb"
  DB_SSL: "true"
