apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerly-backend
  namespace: ledgerly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledgerly-backend
  template:
    metadata:
      labels:
        app: ledgerly-backend
    spec:
      imagePullSecrets:
        - name: acr-secret   # ✅ IMPORTANT FIX

      containers:
        - name: backend
          image: ogccr.azurecr.io/ledgerly-backend:13-fc8100d
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: PORT
              value: "8080"
            - name: APP_ENV
              value: production
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['pod-template-hash']
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ledgerly-secrets
                  key: DATABASE_URL
            - name: DB_SSL
              valueFrom:
                secretKeyRef:
                  name: ledgerly-secrets
                  key: DB_SSL
            - name: CORS_ORIGIN
              value: "*"

          # ✅ FIX: safer probes
          livenessProbe:
          httpGet:
          path: /health
          port: 8080
          initialDelaySeconds: 60   # increase
          periodSeconds: 20

          readinessProbe:
          httpGet:
          path: /ready
          port: 8080
          initialDelaySeconds: 30   # increase
          periodSeconds: 10

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
              