apiVersion: v1
kind: Service
metadata:
  name: ledgerly-frontend
  namespace: ledgerly
spec:
  selector:
    app: ledgerly-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerly-frontend
  namespace: ledgerly
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: ledgerly-frontend
  template:
    metadata:
      labels:
        app: ledgerly-frontend
    spec:
      containers:
        - name: frontend
          image: ledgerly-placeholder.azurecr.io/ledgerly-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
