apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledgerly-ingress
  namespace: ledgerly
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - riskybusiness.online
      secretName: ledgerly-tls
  rules:
    - host: riskybusiness.online
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ledgerly-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ledgerly-frontend
                port:
                  number: 80
